# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

#target 'RunningMap_Gaming' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
#   use_frameworks!

    # Pods for RunningMap_Gaming

#end

target 'RunningMap_LevelMap' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RunningMap_LevelMap

  pod 'Google/SignIn'
  pod 'Firebase'
  pod 'Firebase/Storage'
  pod 'Firebase/AdMob’
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  pod 'FMDB'

  pod 'AFNetworking'

end
